import illustration from "./../../../public/assets/png/illustration1.png";
import illustration2 from "./../../../public/assets/png/illustration2.png";
import illustration3 from "./../../../public/assets/png/illustration3.png";
import illustration4 from "./../../../public/assets/png/illustration4.png";
import illustration5 from "./../../../public/assets/png/illustration5.png";
import illustration6 from "./../../../public/assets/png/illustration6.png";

export const category = [
  {
    illustration: illustration,
    category: "Makanan",
    sub: "Bingung mau makan apa ya? acak disini!",
    list: [
      "Nasi Goreng",
      "Mie Goreng",
      "Ayam Goreng",
      "Bebek Goreng",
      "Ikan Goreng",
      "Mie Rebus",
      "Sop",
      "Soto",
      "Kwetiaw",
      "Rendang",
      "Martabak Manis",
      "Martabak Telor",
      "Bubur Ayam",
      "Bubur Kacang Hijau",
      "Nasi Gila",
      "Ayam Geprek",
      "Ikan Geprek",
      "Pizza",
      "Roti",
      "Ketoprak",
      "Nasi Padang",
      "Fried Chicken",
      "Burger",
      "Kentang Goreng",
      "Tumisan",
    ],
  },
  {
    illustration: illustration2,
    category: "Jajanan",
    sub: "Banyak jajanan bikin bingung, acak disini!",
    list: [
      "Permen",
      "Lolipop",
      "Ciki",
      "Cakwe",
      "Seblak",
      "Gorengan",
      "Kacang Kulit",
      "Kacang Rebus",
      "Bakso",
      "Mie Ayam",
      "Leker",
      "Basreng",
      "Cilok",
      "Baso Tusuk",
      "Somay",
      "Batagor",
      "Es Krim",
      "Cookies",
      "Donat",
    ],
  },
  {
    illustration: illustration3,
    category: "Lokasi",
    sub: "Mau keluar kemana hari ini? acak disini!",
    list: [
      "Kebun Binatang",
      "Tempat Beribadah",
      "Monumen Nasional",
      "Mall",
      "Museum",
      "Rumah Tetangga",
      "Rumah Teman",
      "Sekolah",
      "Taman",
      "Kampus",
      "Kantor",
      "Pom Bensin",
      "Pasar",
      "GOR Bulutangkis",
      "Rumah Sakit",
      "Stadion Bola",
      "Masjid",
      "Hutan",
      "Gereja",
    ],
  },
  {
    illustration: illustration4,
    category: "Minuman",
    sub: "Haus tapi bingung mau minum apa? acak disini!",
    list: [
      "Boba",
      "Capucino Cincau",
      "Es Teh",
      "Minuman Soda",
      "Es Jeruk",
      "Jus Buah",
      "Jus Sayur",
      "Susu",
      "Bir",
      "Minuman Penambah Ion",
      "Air Mineral",
      "Yogurt",
      "Kopi Instan",
      "Es Krim",
    ],
  },
  {
    illustration: illustration5,
    category: "Pakaian",
    sub: "Mau ngedate tapi gatau pake apa? acak disini!",
    list: [
      "T-Shirt",
      "Shirt",
      "Kimono",
      "Kutang",
      "Jaket",
      "Rompi",
      "Polo Shirt",
      "Jubah",
      "Long Sleeve",
      "Kemeja",
      "Jersey",
    ],
  },
  {
    illustration: illustration6,
    category: "Kado",
    sub: "Beli kado apa buat dia ya? acak disini!",
    list: [
      "Pensil",
      "Sendok",
      "Garpu",
      "Lampu",
      "Peralatan Sekolah",
      "Kompor Gas",
      "Blender",
      "Bor",
      "Kipas Angin",
      "Cincin",
      "Boneka",
      "Berlian",
      "Belanja",
    ],
  },
];
