import illustration from "./../../../public/assets/png/illustration1.png";
import illustration2 from "./../../../public/assets/png/illustration2.png";
import illustration3 from "./../../../public/assets/png/illustration3.png";
import illustration4 from "./../../../public/assets/png/illustration4.png";
import illustration5 from "./../../../public/assets/png/illustration5.png";
import illustration6 from "./../../../public/assets/png/illustration6.png";

export const category = [
  {
    illustration: illustration,
    category: "Makanan",
    sub: "Bingung mau makan apa ya? acak disini!",
    list: [
      "🍚 Goreng",
      "🍜 Goreng",
      "🐔 Goreng",
      "🐐 Guling",
      "Sate 🐇",
      "Bebek Goreng",
      "🐟 Goreng",
      "🍜 Rebus",
      "🥘",
      "Soto",
      "🌭",
      "🍳 Ceplok",
      "Kwetiaw",
      "Rendang",
      "Martabak Manis",
      "Martabak Telor",
      "Bubur Ayam",
      "Bubur Kacang Hijau",
      "🍚 Gila",
      "🐔 Geprek",
      "🐟 Geprek",
      "🍕",
      "🥪",
      "Ketoprak",
      "🍚 Padang",
      "Fried 🍗",
      "🍝"
    ],
  },
  {
    illustration: illustration2,
    category: "Jajanan",
    sub: "Banyak jajanan bikin bingung, acak disini!",
    list: [
      "🍬",
      "🍭",
      "Ciki",
      "Cakwe",
      "Seblak",
      "Gorengan",
      "🥜 Kulit",
      "🥜 Rebus",
      "Bakso",
      "🍜 Ayam",
      "Leker",
      "Baso Goreng",
      "Cilok",
      "Baso Tusuk",
      "Somay",
      "Batagor",
      "🍟",
      "🍔"
    ],
  },
  {
    illustration: illustration3,
    category: "Lokasi",
    sub: "Mau keluar kemana hari ini? acak disini!",
    list: [
      "Kebun 🐒",
      "Tempat Beribadah",
      "Monumen Nasional",
      "Mall",
      "🏛️",
      "Taman 🎡🎢",
      "🏠 Tetangga/Teman",
      "🏫",
      "Taman",
      "Kampus",
      "🏢",
      "Pom ⛽",
      "Pasar",
      "🏦",
      "Rumah 🏥",
      "Stadion ⚽",
      "GOR 🏸",
      "🕋",
    ],
  },
  {
    illustration: illustration4,
    category: "Minuman",
    sub: "Haus tapi bingung mau minum apa? acak disini!",
    list: [
      "🧋",
      "Capucino Cincau",
      "🧊 Teh",
      "🥛 Soda",
      "Es 🍹",
      "🧃 Buah",
      "🧃 Sayur",
      "🥛",
      "🍺",
      "Minuman Penambah Ion",
      "Air 🍼",
      "Yogurt",
      "☕ Instan",
      "Es 🍨",
    ],
  },
  {
    illustration: illustration5,
    category: "Pakaian",
    sub: "Mau ngedate tapi gatau pake apa? acak disini!",
    list: [
      "👕",
      "👘",
      "👙",
      "Jaket",
      "🦺",
      "Polo Shirt",
      "Jubah",
      "Long Sleeve",
      "👔",
      "Jersey",
    ],
  },
  {
    illustration: illustration6,
    category: "Kado",
    sub: "Beli kado apa buat dia ya? acak disini!",
    list: [
      "🍴",
      "🥄",
      "💡",
      "Peralatan Sekolah",
      "Kompor Gas",
      "Blender",
      "Bor",
      "Kipas Angin",
      "💍",
      "🧸",
      "🚬",
      "💎",
      "🛍️",
    ],
  },
];
