export const category = [
  {
    category: "Makanan",
    list: [
      "Nasi Goreng",
      "Mie Goreng",
      "Ayam Goreng",
      "Bebek Goreng",
      "Ikan Goreng",
      "Mie Rebus",
      "Sop",
      "Soto",
      "Kwetiaw",
      "Rendang",
      "Martabak Manis/Telor",
      "Bubur Ayam",
      "Bubur Kacang Hijau",
      "Nasi Gila",
      "Ayam Geprek",
      "Ikan Geprek",
      "Pizza",
      "Roti",
      "Ketoprak",
      "Nasi Padang",
      "Fried Chicken",
    ],
  },
  {
    category: "Jajanan",
    list: [
      "Permen",
      "Lolipop",
      "Ciki",
      "Cakwe",
      "Seblak",
      "Gorengan",
      "Kacang Kulit",
      "Kacang Rebus",
      "Bakso",
      "Mie Ayam",
      "Leker",
      "Basreng",
      "Cilok",
      "Baso Tusuk",
      "Somay",
      "Batagor",
    ],
  },
  {
    category: "Lokasi",
    list: [
      "Kebun Binatang",
      "Tempat Beribadah",
      "Monumen Nasional",
      "Mall",
      "Museum",
      "Rumah Tetangga/Teman",
      "Sekolah",
      "Taman",
      "Kampus",
      "Kantor",
      "Pom Bensin",
      "Pasar",
    ],
  },
  {
    category: "Minuman",
    list: [
      "Boba",
      "Capucino Cincau",
      "Es Teh",
      "Minuman Soda",
      "Es Jeruk",
      "Jus Buah",
      "Jus Sayur",
      "Susu",
      "Bir",
      "Minuman Penambah Ion",
      "Air Mineral",
      "Yogurt",
      "Kopi Instan",
      "Es Krim",
    ],
  },
  {
    category: "Pakaian",
    list: [
      "T-Shirt",
      "Kimono",
      "Kutang",
      "Jaket",
      "Rompi",
      "Polo Shirt",
      "Jubah",
      "Long Sleeve",
      "Kemeja",
      "Jersey",
    ],
  },
  {
    category: "Kado",
    list: [
      "Sendok",
      "Garpu",
      "Lampu",
      "Peralatan Sekolah",
      "Kompor Gas",
      "Blender",
      "Bor",
    ],
  },
];
